/**
 * Commit-boundary sanitizer for client-surface section artifacts.
 *
 * Section bodies are generated by models + tools and occasionally carry
 * internal pipeline vocabulary ("corpus", "web_search", "displayable",
 * "evidence gap:", "[unverified]", ...) into buyer-facing string fields. This
 * module strips that vocabulary at the persistence boundary so the committed
 * JSON the reader and share view render never exposes process jargon.
 *
 * It is the deterministic counterpart to the DENY_LIST gate in
 * `scripts/zz-buyer-eval.mjs`: `scrubClientSurfaceText` is guaranteed to
 * produce a string that the gate's `findDenyToken` accepts (see the final
 * residual-strip loop), and `client-surface-sanitizer.test.ts` asserts the
 * token list below stays in parity with the gate.
 *
 * Honest evidence gaps are PRESERVED — they are simply re-expressed in
 * buyer-facing GapNote language ("Not enough public evidence ...") instead of
 * internal markers, and `blockGap*` metadata subtrees (the structured honest
 * gaps) are left untouched, exactly as the gate skips them.
 */

// Mirror of DENY_LIST in scripts/zz-buyer-eval.mjs. Parity is asserted by
// client-surface-sanitizer.test.ts, which reads the script and compares.
export const CLIENT_SURFACE_DENY_TOKENS: readonly string[] = [
  'blockGap',
  'prepass',
  'corpus',
  'verifiedCount',
  'displayable',
  'quarantine',
  'containment',
  'liveness',
  'in this pass',
  'fan-out',
  'keyword_volume',
  'web_search',
  'keyword_trends',
  'tool budget',
  'section badge',
  'evidence gap:',
  '[unverified]',
  '[verified',
  'analysis rework',
  'contradiction status',
];

// Keys whose subtrees are internal-only and are skipped by the gate; we leave
// them byte-identical so tier/flag derivation and honest-gap markers survive.
const SKIP_KEYS = new Set(['verifierSummary', 'decodeRepairs', 'verification', 'review']);

// Internal-only client fields dropped entirely from the persisted body. They
// are optional in every section schema, so removing them keeps the body valid.
const DROP_KEYS = new Set(['internalDetail']);

function isSkipKey(key: string): boolean {
  return SKIP_KEYS.has(key) || key.startsWith('blockGap');
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function isUrlLike(value: string): boolean {
  return /^https?:\/\//i.test(value.trim());
}

// Readable rewrites for the high-frequency tokens, applied before the residual
// strip so common cases read naturally rather than leaving gaps in a sentence.
const READABLE_REWRITES: { pattern: RegExp; replacement: string }[] = [
  { pattern: /^(\s*)evidence gap:\s*/i, replacement: '$1Not enough public evidence: ' },
  { pattern: /\bevidence gap:\s*/gi, replacement: 'limited public evidence: ' },
  { pattern: /\[unverified\]/gi, replacement: '' },
  { pattern: /\[verified[^\]]*\]/gi, replacement: '' },
  { pattern: /\bcorpus\b/gi, replacement: 'company research' },
  { pattern: /web_search/gi, replacement: 'web research' },
  { pattern: /keyword_volume/gi, replacement: 'keyword volume data' },
  { pattern: /keyword_trends/gi, replacement: 'keyword trend data' },
  { pattern: /quarantin\w*/gi, replacement: 'withheld' },
  { pattern: /\bdisplayable\b/gi, replacement: 'available' },
  { pattern: /verifiedcount/gi, replacement: 'verified count' },
];

/**
 * Mirror of `findDenyToken` in scripts/zz-buyer-eval.mjs — returns the first
 * deny token present in `value`, or null. Exported so the backfill script and
 * tests can assert against the exact gate semantics.
 */
export function findInternalVocabularyToken(value: string): string | null {
  const lower = value.toLowerCase();
  for (const token of CLIENT_SURFACE_DENY_TOKENS) {
    const lowerToken = token.toLowerCase();
    if (lowerToken === 'evidence gap:') {
      if (lower.trim().startsWith('evidence gap:')) return token;
      continue;
    }
    if (lower.includes(lowerToken)) return token;
  }
  return null;
}

function stripToken(text: string, token: string): string {
  if (token === 'evidence gap:') {
    return text.replace(/^\s*evidence gap:\s*/i, '');
  }
  const escaped = escapeRegExp(token);
  // Remove the whole containing word for single-token vocab so inflected forms
  // ("quarantined", "blockGaps") don't leave fragments; literal for phrases.
  const pattern = /\s/.test(token) ? escaped : `[\\w-]*${escaped}[\\w-]*`;
  return text.replace(new RegExp(pattern, 'gi'), '');
}

// Buyer-facing fallback for an entire string that is raw validator output.
const CLIENT_GAP_FALLBACK = 'Not enough public evidence was found for this point.';

// Signatures of raw validator / Zod / tolerant-decode messages that must never
// reach a buyer (e.g. "VoiceOfCustomerSectionOutputBody failed tolerant
// decode... sourceUrls may be empty only when basis is assumption"). When a
// string is recognisably validator output we replace the WHOLE string with a
// clean GapNote rather than splice it, since the sentence is structured noise.
const VALIDATOR_MESSAGE_SIGNATURES: readonly RegExp[] = [
  /failed tolerant decode/i,
  /tolerant[- ]decode/i,
  /\bzoderror\b/i,
  /invalid input:\s*expected/i,
  /too (?:small|big):\s*expected/i,
  /expected (?:array|string|object|number|boolean|record)\b.{0,48}\breceived\b/i,
  /may be empty only when basis is/i,
  /\b\w+(?:Schema|SectionOutputBody)\b/,
  /\bhave \d+[,;].{0,40}\b(?:need|add)\b/i,
];

function looksLikeValidatorMessage(value: string): boolean {
  return VALIDATOR_MESSAGE_SIGNATURES.some((signature) => signature.test(value));
}

/**
 * Removes internal pipeline vocabulary from a single client-surface string,
 * re-expressing honest gaps in buyer language. The result is guaranteed to
 * satisfy `findInternalVocabularyToken(result) === null`, and raw validator /
 * Zod / decode output is replaced wholesale with a buyer-facing gap note.
 */
export function scrubClientSurfaceText(value: string): string {
  if (value.length === 0 || isUrlLike(value)) return value;
  if (looksLikeValidatorMessage(value)) return CLIENT_GAP_FALLBACK;

  let out = value;
  for (const { pattern, replacement } of READABLE_REWRITES) {
    out = out.replace(pattern, replacement);
  }

  // Guarantee: remove any residual deny token the readable rewrites missed.
  let guard = 0;
  let token = findInternalVocabularyToken(out);
  while (token !== null && guard < 64) {
    out = stripToken(out, token);
    token = findInternalVocabularyToken(out);
    guard += 1;
  }

  out = out.replace(/\s{2,}/g, ' ').replace(/\s+([.,;:!?])/g, '$1').trim();
  return out.length > 0 ? out : 'Not available.';
}

/**
 * Markdown-safe vocab scrub for the long GLM narrative blob persisted to the
 * section card (§4.1 RAW un-caged GLM). It removes internal pipeline vocabulary
 * exactly like {@link scrubClientSurfaceText}, but differs in two ways that
 * matter for multi-paragraph prose:
 *   1. It PRESERVES newlines — collapsing only horizontal whitespace runs per
 *      line — so markdown structure (headings, lists, paragraphs) survives.
 *   2. It does NOT wholesale-replace on a validator-message signature. That
 *      replace exists to nuke short structured-noise leaves; on 2,000-word
 *      research prose a single incidental "...Schema" word would otherwise wipe
 *      the entire body. Source-class labeling, not this scrub, is the anti-fab.
 * The result is guaranteed free of deny tokens line-by-line.
 */
// Residual internal-jargon tokens to remove from the GLM markdown body AFTER
// READABLE_REWRITES. DELIBERATELY EXCLUDES the genuinely-English deny tokens
// ('containment', 'liveness') — Ramp is a cost-CONTAINMENT company and 'liveness'
// is real eng prose; the general substring strip would eat 'cost containment' ->
// 'cost '. These are matched on WORD boundaries (not substring) so inflected
// real words are never clipped. Tokens already handled by READABLE_REWRITES
// (corpus, web_search, keyword_volume/trends, displayable, quarantine, evidence
// gap:, [unverified]/[verified]) are omitted here.
const MARKDOWN_RESIDUAL_DENY_TOKENS: readonly string[] = [
  'blockGap',
  'prepass',
  'verifiedCount',
  'in this pass',
  'fan-out',
  'tool budget',
  'section badge',
  'analysis rework',
  'contradiction status',
];

export function scrubMarkdownVocabOnly(value: string): string {
  if (value.length === 0) return value;

  let out = value;
  for (const { pattern, replacement } of READABLE_REWRITES) {
    out = out.replace(pattern, replacement);
  }
  for (const token of MARKDOWN_RESIDUAL_DENY_TOKENS) {
    out = out.replace(new RegExp(`\\b${escapeRegExp(token)}\\b`, 'gi'), '');
  }

  return out
    .split('\n')
    .map((line) => {
      // Preserve LEADING indentation so nested lists and indented code blocks
      // keep their structure; collapse only INTERIOR horizontal whitespace.
      const lead = line.match(/^[ \t]*/)?.[0] ?? '';
      const rest = line
        .slice(lead.length)
        .replace(/[ \t]{2,}/g, ' ')
        .replace(/[ \t]+([.,;:!?])/g, '$1');
      return lead + rest;
    })
    .join('\n');
}

function sanitizeNode(node: unknown): unknown {
  if (typeof node === 'string') return scrubClientSurfaceText(node);
  if (Array.isArray(node)) return node.map((item) => sanitizeNode(item));
  if (node !== null && typeof node === 'object') {
    const result: Record<string, unknown> = {};
    for (const [key, child] of Object.entries(node as Record<string, unknown>)) {
      if (DROP_KEYS.has(key)) continue;
      result[key] = isSkipKey(key) ? child : sanitizeNode(child);
    }
    return result;
  }
  return node;
}

/**
 * Returns a deep copy of a section artifact (or any client-surface payload)
 * with internal vocabulary scrubbed from every non-skipped string leaf and
 * internal-only fields dropped. Numbers, booleans, URLs, and the internal
 * metadata subtrees (`verification`, `review`, `blockGap*`, ...) are preserved
 * unchanged.
 */
export function sanitizeArtifactForClientSurface<T>(artifact: T): T {
  return sanitizeNode(artifact) as T;
}
