-- Create Blueprints Table
-- Migration: 20260125_create_blueprints_table.sql
-- Stores user-generated strategic blueprints with input data and output

-- Create blueprints table
CREATE TABLE IF NOT EXISTS public.blueprints (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  title text NOT NULL,
  input_data jsonb,
  output jsonb NOT NULL,
  generation_metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Add index for querying blueprints by user
CREATE INDEX IF NOT EXISTS idx_blueprints_user_id
ON public.blueprints(user_id);

-- Add index for ordering by creation date
CREATE INDEX IF NOT EXISTS idx_blueprints_created_at
ON public.blueprints(created_at DESC);

-- Add updated_at trigger
CREATE OR REPLACE FUNCTION update_blueprints_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS blueprints_updated_at ON public.blueprints;
CREATE TRIGGER blueprints_updated_at
  BEFORE UPDATE ON public.blueprints
  FOR EACH ROW
  EXECUTE FUNCTION update_blueprints_updated_at();

-- Enable RLS
ALTER TABLE public.blueprints ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view their own blueprints
CREATE POLICY "Users can view their own blueprints"
ON public.blueprints FOR SELECT
TO authenticated
USING (user_id = auth.jwt() ->> 'sub');

-- RLS Policy: Users can insert their own blueprints
CREATE POLICY "Users can insert their own blueprints"
ON public.blueprints FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.jwt() ->> 'sub');

-- RLS Policy: Users can update their own blueprints
CREATE POLICY "Users can update their own blueprints"
ON public.blueprints FOR UPDATE
TO authenticated
USING (user_id = auth.jwt() ->> 'sub')
WITH CHECK (user_id = auth.jwt() ->> 'sub');

-- RLS Policy: Users can delete their own blueprints
CREATE POLICY "Users can delete their own blueprints"
ON public.blueprints FOR DELETE
TO authenticated
USING (user_id = auth.jwt() ->> 'sub');

-- Comments for documentation
COMMENT ON TABLE public.blueprints IS
'Stores user-generated strategic blueprints with full input/output data';

COMMENT ON COLUMN public.blueprints.user_id IS
'Clerk user ID (from auth.jwt() sub claim)';

COMMENT ON COLUMN public.blueprints.title IS
'Display title for the blueprint, typically derived from industry or business name';

COMMENT ON COLUMN public.blueprints.input_data IS
'JSONB storage for the onboarding form data used to generate this blueprint';

COMMENT ON COLUMN public.blueprints.output IS
'JSONB storage for the full StrategicBlueprintOutput generated by AI';

COMMENT ON COLUMN public.blueprints.generation_metadata IS
'Optional metadata about generation: totalTime, totalCost, generatedAt, etc.';
